server:
  port: 8089

spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 1234
tomcat:
    initialSize: 1
    min-idle: 1
    max-idle: 20
    max-wait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

logging:
    file: logs/demo.log

#swagger
springfox:
    documentation:
        swagger:
            v2:
                path: /api-docs
#mybatis
mybatis:
    mapper-locations: classpath*:mybatis/*.xml
    type-aliases-package: com.yy.springbootswagger.entity